services:
  db:
    image: postgres:14-alpine
    container_name: upskilling-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      POSTGRES_DB: ${DB_NAME:-upskilling_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upskilling-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-mysecretpassword}
      DB_NAME: ${DB_NAME:-upskilling_db}
    depends_on:
      - db
    command: sh -c "/setup && ./upskilling-server" # Executa o seeder e depois a aplicação

volumes:
  postgres_data:
